---
abstract: 'Provides a consumable Reflex-based multiplexing TCP server behavior'
author:
  - 'Nicholas R. Perez <nperez@cpan.org>'
build_requires:
  Moose: 0
  POSIX: 0
  Reflex::Base: 0
  Reflex::Client: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Reflexive-Role-TCPServer
requires:
  IO::Socket::INET: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Params::Validate: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Structured: 0
  POE::Filter::Stream: 0
  Reflex::Callbacks: 0
  Reflex::Role: 0
  Reflex::Role::Accepting: 0
  Reflexive::Role::Collective: 0
  Reflexive::Stream::Filtering: 0
  Try::Tiny: 0
resources:
  repository: git://nickandperla.net/reflexive-role-tcpserver.git
version: 1.110100
